-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 15:18:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aci
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aci
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aci` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aci` ;

-- -----------------------------------------------------
-- Table `aci`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aci`.`Categories` (
  `identifier` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(30) NOT NULL,
  `date_registered` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `priority` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`identifier`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) VISIBLE,
  UNIQUE INDEX `denomination_UNIQUE` (`denomination` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aci`.`Insights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aci`.`Insights` (
  `identifier` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Category_identifier` TINYINT UNSIGNED NOT NULL,
  `denomination` VARCHAR(100) NOT NULL,
  `date_registered` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`identifier`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) VISIBLE,
  UNIQUE INDEX `denomination_UNIQUE` (`denomination` ASC) VISIBLE,
  INDEX `fk_Alert_Category1_idx` (`Category_identifier` ASC) VISIBLE,
  CONSTRAINT `fk_Alert_Category1`
    FOREIGN KEY (`Category_identifier`)
    REFERENCES `aci`.`Categories` (`identifier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aci`.`Connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aci`.`Connections` (
  `identifier` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `key` TINYTEXT NOT NULL,
  `date_joined` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`identifier`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aci`.`Alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aci`.`Alerts` (
  `identifier` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Connection_identifier` SMALLINT UNSIGNED NOT NULL,
  `Insight_identifier` SMALLINT UNSIGNED NOT NULL,
  `is_solved` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `date_registered` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resource_arn` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`identifier`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) VISIBLE,
  INDEX `fk_Instance_Connection1_idx` (`Connection_identifier` ASC) VISIBLE,
  INDEX `fk_Instance_Insight_idx` (`Insight_identifier` ASC) VISIBLE,
  FULLTEXT INDEX `Identifier_resource_arn` (`resource_arn`) VISIBLE,
  CONSTRAINT `fk_Instance_Alert1`
    FOREIGN KEY (`Insight_identifier`)
    REFERENCES `aci`.`Insights` (`identifier`),
  CONSTRAINT `fk_Instance_Connection1`
    FOREIGN KEY (`Connection_identifier`)
    REFERENCES `aci`.`Connections` (`identifier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aci`.`Trainings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aci`.`Trainings` (
  `identifier` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `date_registered` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL DEFAULT 0,
  `Alert_identifier` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`identifier`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) VISIBLE,
  INDEX `Alert_identifier_idx` (`Alert_identifier` ASC) VISIBLE,
  CONSTRAINT `Alert_identifier`
    FOREIGN KEY (`Alert_identifier`)
    REFERENCES `aci`.`Alerts` (`identifier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
